// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxCm-rGMtozZaN-OI6N7C6UMUPWumzHgQ',
    appId: '1:993368974370:web:ca81c1988287bdd2dbd67b',
    messagingSenderId: '993368974370',
    projectId: 'halolapor-ef303',
    authDomain: 'halolapor-ef303.firebaseapp.com',
    storageBucket: 'halolapor-ef303.appspot.com',
    measurementId: 'G-Z2NYGQ8Q47',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPciiqSBL2vr7dB_0NKCUeIjcgccIM26Q',
    appId: '1:993368974370:ios:2e8df22969fd875fdbd67b',
    messagingSenderId: '993368974370',
    projectId: 'halolapor-ef303',
    storageBucket: 'halolapor-ef303.appspot.com',
    iosClientId: '993368974370-fpoqbiov7m71i7v7ujjahlhben44lbt5.apps.googleusercontent.com',
    iosBundleId: 'com.kodenata',
  );
}
